USE OnlineShop_STG;
GO

DELETE FROM Shipment_STG;
DELETE FROM Payment_STG;
DELETE FROM OrderItem_STG;
DELETE FROM Review_STG;
DELETE FROM Order_STG;
DELETE FROM Product_STG;
DELETE FROM Supplier_STG;
DELETE FROM Customer_STG;
GO